placeholder/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as django_views #currently using default django views for login and logout, might want to change eventually, or like, effort -emily




app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', django_views.login, name='login',
        kwargs={'template_name': 'accounts/login.html'}),
    url(r'^logout/$', django_views.logout, {'next_page': '/'}), #redirects home page on logout
    url(r'^editprofile/$', views.editProfile, name='editProfile'),
    url(r'^changepassword/$', views.changePassword),
]

placeholder/placeholder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import Home
from submissions import views
from django.contrib.auth import views as django_views #for logout and password stuff, which should probs be in accounts/urls.py but I couldn't get it to work - emily


import comments.views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', django_views.logout, {'next_page': '/'}),
    url(r'^(?P<id>\d+)/comments/', include('comments.urls')),
    url(r'', include('submissions.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^accounts/password/reset/$', django_views.password_reset, name='password_reset', 
        kwargs={'template_name': 'accounts/password_reset.html'
        }),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        django_views.password_reset_confirm,  name='password_reset_confirm',
        kwargs={'post_reset_redirect' : '/user/password/done/'}),
    url(r'^accounts/password/reset/complete/$', django_views.password_reset_complete, name='password_reset_complete',
         kwargs={'template_name': 'accounts/password_reset_complete.html' }),
    url(r'^accounts/password/reset/done/$', django_views.password_reset_done, name='password_reset_done',
         kwargs={'template_name': 'accounts/password_reset_done.html' }),
    url(r'^accounts/password/change/$', django_views.password_change, 
        kwargs= {'template_name': 'accounts/password_change.html'})
]

placeholder/accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	department = models.CharField(max_length=100)
	GENDER_CHOICES = (('M', 'Male'),('F', 'Female'),('N/A', 'N/A'),)
	gender = models.CharField(max_length=3, choices=GENDER_CHOICES, default='N/A')
	points = models.IntegerField(default=1)

def create_profile(sender, **kwargs):
	user = kwargs["instance"]
	if kwargs["created"]:
		user_profile = UserProfile(user=user)
		user_profile.save()
post_save.connect(create_profile, sender=User)

placeholder/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
 
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

placeholder/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import UserForm
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.contrib.auth import update_session_auth_hash


# Create your views here.
@login_required() 
def index(request):
    user = request.user
    username = user.username
    name = str(user.first_name) + " " + str(user.last_name)
    email = user.email
    department = UserProfile(user).department
    print department

    return render(request, 'accounts/index.html', {
    'user' : request.user,
    'username' : user.username,
    'email' : user.email,
    'name' : name,
    'department' : department,
        })


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
 
    return render(request, 'accounts/signup.html', {
        'form': form,
        })

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            render(request, 'accounts/success.html')
        else:
            render(request, 'accounts/failed_disabled.html')
    else:
        render(request, 'accounts/failed_invalid.html')

@login_required() 
def editProfile(request):

    user = request.user

    user_form = UserForm(instance=user)
 
    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('department', 'gender'))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)
 
            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)
 
                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect('/accounts/')
 
        return render(request, "accounts/editProfile.html", {
            "user": user,
            "user_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied

@login_required
def changePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect('/accounts/')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, "accounts/password_change.html", {
        'form': form,
    })

placeholder/accounts/templates/accounts/editProfile.html
{% extends "base.html" %}

{% block content %}
	<div id="manage">
		<h1>Manage Your Account</h1>
		<form action="" method="POST">{% csrf_token %}
             {{ user_form.as_p }}
             {{ formset.management_form }}
             {{ formset.as_p }}
             <input type="submit" value="submit"/>
             <input type="hidden" name="next" value="{{ next }}" />
        </form>
 	</div>
{% endblock %}

placeholder/accounts/templates/accounts/failed_disabled.html
{% extends "base.html" %}

{% block title %}Accounts{% endblock %}

{% block content %}

Account is disabled

{% endblock %}

placeholder/accounts/templates/accounts/failed_invalid.html
{% extends "base.html" %}

{% block title %}Accounts{% endblock %}

{% block content %}

Failed to login, invalid username or password

{% endblock %}

placeholder/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Accounts{% endblock %}

{% block content %}
<li><a href="editprofile/">Edit profile</a></li>
<li><a href="password/change/">Change Password</a></li>

<h2>{{ user.username }}</h2>
<h3>About:</h3>
<li><p>Department: {{ user.userprofile.department }}</p></li>
<li><p>Name: {{ user.first_name }} {{ user.last_name }}</p></li>
<li><p>email: {{ user.email }}</p></li>
<li><p>points: {{ user.userprofile.points }}</p></li>

{% endblock %}

placeholder/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>

{% endif %}

<div id="login-form">
<h1>Login</h1>

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<p>
    {{ form.username.label_tag }}
</p>
{{ form.username }}
<p>
    {{ form.password.label_tag }}
</p>
{{ form.password }}

<input type="hidden" name="next" value="{{ next }}" />
{% if form.errors %}
<h5>Your username and password didn't match. Please try again.</h5>
<p id="submit" style="margin-top:23px"><input type="submit" value="login" /></p>
{% else %}
<p id="submit"><input type="submit" value="login" /></p>
{% endif %}
</form>
</div>

<p><a href="{% url 'password_reset' %}">Forgot password?</a></p>

{% endblock %}

placeholder/accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}
<form action="" method="post"> 
{% csrf_token %}
<li>
	<p>
		{{ form.old_password.errors }}
		<label for="old_password">Old password:</label>
		{{ form.old_password }}
	</p>
	<p>
		{{ form.new_password1.errors }}
		<label for="new_password1">New password:</label>
		{{ form.new_password1 }}
		
	</p>
	<p>
		{{ form.new_password2.errors }}
		<label for="new_password2">Confirm password:</label>
		{{ form.new_password2 }}
		
	</p>
	<p>
		<input type="submit" value="Change my password" />
	</p>
</li>
</form>

{% endblock %}

placeholder/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}


{% block content %}
<p>Please specify your email address to receive instructions for resetting it.</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset password" /></p>
</form>
{% endblock %}

placeholder/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset successful{% endblock %}

{% block content %}
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>
{% endblock %}

placeholder/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Setting New password{% endblock %}

{% block content %}
    {% if validlink %}
        <p>Please enter your new password twice.<br />
           So we can verify you typed it in correctly.</p>
        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset unsuccessful</h1>
        <p>The password reset link was invalid, <br />
        possibly because it has already been used. <br />
        Please request a new password reset.</p>
    {% endif %}
{% endblock %}

placeholder/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}Password reset successful{% endblock %}

{% block content %}
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>
{% endblock %}

placeholder/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
<div id="sign-up">
  <h1>Create an account</h1>

  <form action="" method="post"> 
  {% csrf_token %}
      {{ form.as_p }}
      <div id="submit"><input type="submit" value="Create account"></div>
  </form>
</div>
{% endblock %}